How to/manage healthcare element
icure/medtech-docs pull request #12
Opened 2022-09-30 14:32 UTC by TestaDiRapa

2022-09-30 16:07 UTC, aduchate requested changes

2022-09-30 16:07 UTC, aduchate commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +Note that the Filter method will return a PaginatedList which contains a number of element up to the maximum you specify
```suggestion
The `filter` method returns a PaginatedList that contains at most the number of elements stated
```

2022-09-30 16:07 UTC, aduchate commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +Finally, you can also retrieve all the Healthcare Elements related to a specific patient that the current Data Owner
```suggestion
You can also retrieve all the Healthcare Elements belonging to a specific patient that the current Data Owner 
```

2022-10-17 12:09 UTC, lisatr2812 requested changes

2022-10-17 12:09 UTC, lisatr2812 commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +Even if you associate a Healthcare Element to a Patient, the Patient does not have access to it unless you give access
Even if you associate a Healthcare Element to a Patient, the Patient does not automatically have access to it. You need to explicitly give access to the patient user to this created Healthcare Element by calling the service `giveAccessTo`.

2022-10-17 12:09 UTC, lisatr2812 commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +After creating the Healthcare Element, the Healthcare Professional shares it with the Patient.
After creating the Healthcare Element, the Healthcare Professional can share it with the Patient.

Plus, add more detail / a note to explain that a Patient can give access to a HCP, to another patient, a hcp can give access to a patient, to another hcp, ... it's not one way

2022-10-17 12:09 UTC, lisatr2812 commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +A single Healthcare Element can be retrieved from the Backend using its id.
A single Healthcare Element can be retrieved from the iCure Back-end using its id.

2022-10-17 12:09 UTC, lisatr2812 commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +const createdHealthcareElement = await api.healthcareElementApi.createOrModifyHealthcareElement(
I would not put the create in the code sample : Reuse the one you previously created in the other code samples

2022-10-17 12:09 UTC, lisatr2812 commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +Some fields, like id and rev, cannot be modified.
Precise all fields that can't be modified.

2022-10-17 12:09 UTC, lisatr2812 commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +If the operation is successful, the method returns the updated Healthcare Element as it is stored in the Backend.
If the operation is successful, the method returns the updated Healthcare Element.

2022-10-17 12:09 UTC, lisatr2812 commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +To update a Healthcare Element, both id and rev fields must be valid.
What does it mean that id and rev must be valid ? Explain to the user

2022-10-17 12:09 UTC, lisatr2812 commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +You can learn more about filters in the how to.
I think there's already the empty file, so that you can add the link, even if it is empty for now

2022-10-17 12:09 UTC, lisatr2812 commented on sdks/how-to/how-to-manage-healthcare-elements.md
> +To retrieve more Healthcare Elements, you can call the same method again, using the startDocumentId provided in the previous
To retrieve more Healthcare Elements, you can call the same method again, using the startDocumentId provided in the previous PaginatedList.

2022-10-18 08:24 UTC, merged